### ISSUE TITLE
Use MongoDB as a DB is bad wording 

### ISSUE THREAD

**Issue by kayvan61** [garzarobm/EE461L#3]
Using MongoDB is poor wording. should be changed to something along the lines of "use MongoDB as a Database framework/backend" or "Create a database with MongoDB". Also add details as what constitutes using MongoDB for our project with a concrete goal (have a query-able Database populated with test data; have a scheme established; have some test scripts that read and write data to the test database).

"'Use MongoDB as a DB' is poorly worded and does not explain to me what I need to grade for that. Explain concretely what this means"

**Comment by garzarobm** [comment]
We decided to change this in the Phase
